### PR TITLE
attempt to get hyperlinks recognized

### PR DESCRIPTION
**Pull request by wibeasley**
I don't see why neither link in this Rmd paragraph had been converted to an html hyperlink.  The resulting md file looks fine.

Maybe this trailing slash will help the first one?

image

### CODE REVIEW

**Comment by jennybc** [comment]
This looks like something where you could get to the bottom of it elsewhere, i.e. in another (toy) repo. When/if you sort it out, could you render `README.Rmd` so the PR contains `.Rmd` and `.md`? Thanks!

**Comment by wibeasley** [comment]
The links now work, but there are a bunch of unrelated differences, that are probably related to newer versions of R Markdown, pandoc, & tibble.

The only real difference I see is the new md/html lacks the TOC, which apparently is a known issue for the `github_document` output of R Markdown: https://github.com/rstudio/rmarkdown/issues/1211#issuecomment-367009937.

Is the TOC important to you?

**Comment by jennybc** [comment]
I fiddled with it a bit to hold on to our TOC.

Thanks!

**Comment by wibeasley** [comment]
Sorry I led you down this path if this was more trouble than two hyperlinks were worth.

**Pull request merged**
